#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts /tmp/hosts.bak
grep -v "localhost\|facebook.com" /tmp/hosts.bak > /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
